language: node_js

node_js:
  - "0.10"

env:
  global:
    - MONGO_REPO="http://repo.mongodb.org/apt/ubuntu"
    - REPO_TYPE="$(lsb_release -sc)/mongodb-org/3.0 multiverse"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb.list"
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"

before_install:
  - sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
  - echo "deb ${MONGO_REPO} ${REPO_TYPE}" | sudo tee ${SOURCES_LOC}
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - sleep 15
  - mongod --version

before_script:
  - mongorestore --version
  - mongorestore --drop --db animus --dir src/test/dump/animus

after_success:
  - sudo service mongod stop
  - gulp manifest

deploy:
  provider: heroku
  app: crucible-animus
  skip-cleanup: true
  api_key:
    secure: LmQALYSleSoQTSy7af52VUMbFTdYEbimrERy9yYXl6IU1uLUh7oN8m37NGu+lS7MFvoZrSst0UlYp3YabaugEDrPmyMOXJAl/pBdd6Gge+i+7PRN4UDBH6D4kY7KxqMZ9gngqMAGHjHvKwERJ1j/wZH1JzZoiW273tl3BfwzUgQ=
  on:
    repo: cruciblelarp/animus
    branch: master
